Version: '2020-06-01'
Type: Resource
ResourceType:
  From: ALIYUN::SLS::LogtailConfig
  To: alicloud_logtail_config
Properties:
  RawConfigData:
    Ignore: true
  CloneFrom:
    Ignore: true
  LogtailConfigName:
    Ignore: true
  LogstoreName:
    Ignore: true
  ProjectName:
    Ignore: true
Attributes:
  Endpoint:
    Ignore: true
  LogtailConfigName:
    Ignore: true
  AppliedMachineGroups:
    Ignore: true
