Version: '2020-06-01'
Type: Resource
ResourceType:
  From: ALIYUN::FC3::AsyncInvokeConfig
  To: alicloud_fcv3_async_invoke_config
Properties:
  AsyncTask:
    Ignore: true
  DestinationConfig:
    Ignore: true
  FunctionName:
    To: function_name
  MaxAsyncEventAgeInSeconds:
    Ignore: true
  MaxAsyncRetryAttempts:
    Ignore: true
