Version: '2020-06-01'
Type: Resource
ResourceType:
  From: ALIYUN::Config::DeliveryChannel
  To: alicloud_config_delivery_channel
Properties:
  DeliveryChannelAssumeRoleArn:
    To: delivery_channel_assume_role_arn
  DeliveryChannelCondition:
    To: delivery_channel_condition
  DeliveryChannelName:
    To: delivery_channel_name
  DeliveryChannelTargetArn:
    To: delivery_channel_target_arn
  DeliveryChannelType:
    To: delivery_channel_type
  Description:
    To: description
Attributes:
  DeliveryChannelId:
    To: id
