Version: '2020-06-01'
Type: Resource
ResourceType:
  From: ALIYUN::CDN::DomainConfig
  To: alicloud_cdn_domain_config
Properties:
  DomainNames:
    To: domain_name
  FunctionList:
    Ignore: true
Attributes: {}
