Version: '2020-06-01'
Type: Resource
ResourceType:
  From: alicloud_cloud_sso_access_configuration_provisioning
  To: ALIYUN::CloudSSO::AccessConfigurationProvision
Properties:
  access_configuration_id:
    To: AccessConfigurationId
  directory_id:
    To: DirectoryId
  status:
    Ignore: true
  target_id:
    To: TargetId
  target_type:
    To: TargetType
Attributes:
  id:
    Ignore: true
  access_configuration_id:
    Ignore: true
  directory_id:
    Ignore: true
  status:
    Ignore: true
  target_id:
    Ignore: true
  target_type:
    Ignore: true
