Version: '2020-06-01'
Type: Resource
ResourceType:
  From: alicloud_ess_scaling_configuration
  To: ALIYUN::ESS::ScalingConfiguration
Properties:
  active:
    Ignore: true
  credit_specification:
    To: CreditSpecification
  data_disk:
    To: DiskMappings
    Type: List
    Schema:
      Size:
        To: Size
      auto_snapshot_policy_id:
        To: AutoSnapshotPolicyId
      category:
        To: Category
      delete_with_instance:
        Ignore: true
      description:
        To: Description
      device:
        To: Device
      encrypted:
        To: Encrypted
      kms_key_id:
        To: KMSKeyId
      name:
        To: DiskName
      snapshot_id:
        To: SnapshotId
  deletion_protection:
    Ignore: true
  enable:
    Ignore: true
  force_delete:
    Ignore: true
  host_name:
    To: HostName
  image_id:
    To: ImageId
  image_name:
    To: ImageName
  image_options_login_as_non_root:
    To: ImageOptionsLoginAsNonRoot
  instance_description:
    To: InstanceDescription
  instance_ids:
    To: InstanceId
  instance_name:
    To: InstanceName
  instance_pattern_info:
    Ignore: true
  instance_type:
    To: InstanceType
  instance_type_override:
    Ignore: true
  instance_types:
    To: InstanceTypes
    Type: List
  internet_charge_type:
    To: InternetChargeType
  internet_max_bandwidth_in:
    To: InternetMaxBandwidthIn
  internet_max_bandwidth_out:
    To: InternetMaxBandwidthOut
  io_optimized:
    To: IoOptimized
  is_outdated:
    Ignore: true
  key_name:
    To: KeyPairName
  kms_encrypted_password:
    Ignore: true
  kms_encryption_context:
    Ignore: true
  override:
    Ignore: true
  password:
    To: Password
  password_inherit:
    To: PasswordInherit
  resource_group_id:
    To: ResourceGroupId
  role_name:
    To: RamRoleName
  scaling_configuration_name:
    To: ScalingConfigurationName
  scaling_group_id:
    To: ScalingGroupId
  security_enhancement_strategy:
    To: SecurityEnhancementStrategy
  security_group_id:
    To: SecurityGroupId
  security_group_ids:
    To: SecurityGroupIds
    Type: List
  spot_duration:
    To: SpotDuration
  spot_price_limit:
    Ignore: true
  spot_strategy:
    To: SpotStrategy
  substitute:
    Ignore: true
  system_disk_auto_snapshot_policy_id:
    To: SystemDiskAutoSnapshotPolicyId
  system_disk_category:
    To: SystemDiskCategory
  system_disk_description:
    To: SystemDiskDescription
  system_disk_encrypt_algorithm:
    To: SystemDiskEncryptAlgorithm
  system_disk_encrypted:
    To: SystemDiskEncrypted
  system_disk_kms_key_id:
    Ignore: true
  system_disk_name:
    Ignore: true
  system_disk_performance_level:
    To: SystemDiskPerformanceLevel
  system_disk_provisioned_iops:
    To: SystemDiskProvisionedIops
  system_disk_size:
    To: SystemDiskSize
  tags:
    To: TagList
  user_data:
    To: UserData
Attributes:
  id:
    To: ScalingConfigurationId
  active:
    Ignore: true
  credit_specification:
    Ignore: true
  data_disk:
    Ignore: true
  deletion_protection:
    Ignore: true
  force_delete:
    Ignore: true
  host_name:
    Ignore: true
  image_id:
    Ignore: true
  image_name:
    Ignore: true
  image_options_login_as_non_root:
    Ignore: true
  instance_description:
    Ignore: true
  instance_name:
    Ignore: true
  instance_type:
    Ignore: true
  instance_types:
    Ignore: true
  internet_charge_type:
    Ignore: true
  internet_max_bandwidth_in:
    Ignore: true
  internet_max_bandwidth_out:
    Ignore: true
  key_name:
    Ignore: true
  override:
    Ignore: true
  password_inherit:
    Ignore: true
  resource_group_id:
    Ignore: true
  role_name:
    Ignore: true
  scaling_configuration_name:
    Ignore: true
  scaling_group_id:
    To: ScalingGroupId
  security_enhancement_strategy:
    Ignore: true
  security_group_id:
    Ignore: true
  security_group_ids:
    Ignore: true
  spot_duration:
    Ignore: true
  spot_price_limit:
    Ignore: true
  spot_strategy:
    Ignore: true
  system_disk_auto_snapshot_policy_id:
    Ignore: true
  system_disk_category:
    Ignore: true
  system_disk_description:
    Ignore: true
  system_disk_encrypt_algorithm:
    Ignore: true
  system_disk_encrypted:
    Ignore: true
  system_disk_kms_key_id:
    Ignore: true
  system_disk_name:
    Ignore: true
  system_disk_performance_level:
    Ignore: true
  system_disk_provisioned_iops:
    Ignore: true
  system_disk_size:
    Ignore: true
  tags:
    Ignore: true
  user_data:
    Ignore: true
