name: Run Tests

on:
  push:
    paths-ignore:
      - 'website/**'
      - '*.md'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'website/**'
      - '*.md'
      - '**/*.md'

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', '3.14' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v4
      - name: Install dependencies
        run: |
          uv venv --python ${{ matrix.python-version }}
          uv pip install -e ".[dev]"
          uv pip install libterraform==0.8.2
      - name: Run tests
        run: |
          uv run pytest tests
